#!/usr/bin/env python3
"""
Generates the committed signing vectors from ``sandbox-security-attestation-signing.md``.

THIS IS A THIRD IMPLEMENTATION, AND THAT IS THE POINT.

The producer in ``services/runner`` and the verifier in ``apps/api`` each implement the contract
independently, and the vectors in ``fixtures/sandbox-security-attestation-signing/`` are what they are both
checked against. If those vectors were generated by either of them, the check would be that implementation
agreeing with itself -- which is exactly what having two implementations was supposed to avoid.

So this is written from the contract document, in a different language, using a different crypto library. When
all three agree byte for byte, the agreement is evidence. When they disagree, the contract is ambiguous and
the fix is the contract.

Not part of any build. It is run by hand when the contract changes, and what it writes is committed --
generating the vectors during the build would mean the implementations were checked against whatever the
generator said today rather than against a value fixed in the repository and reviewed.

Run:
    python3 -m venv /tmp/kaas-vectors && /tmp/kaas-vectors/bin/pip install cryptography
    /tmp/kaas-vectors/bin/python packages/api-contracts/scripts/generate-signing-vectors.py

`cryptography` is deliberately not a repository dependency: this is a cross-check tool, and pinning a second
crypto library into the build to verify the first one would defeat the point of the independence.
"""

import base64
import hashlib
import json
import pathlib
import struct

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

FIXTURES = pathlib.Path(__file__).resolve().parent.parent / "fixtures" / "sandbox-security-attestation-signing"

DOMAIN = "KAAS_SANDBOX_SECURITY_ATTESTATION_V4"
ABSENT = " ABSENT"


def emit(text):
    """LABEL(s) and VALUE(s) are the same primitive: 4-byte big-endian length, then UTF-8 bytes."""
    encoded = text.encode("utf-8")
    return struct.pack(">I", len(encoded)) + encoded


def canonical_preimage(payload):
    out = bytearray()
    out += emit(DOMAIN)

    for label, field in [
        ("SCHEMA_VERSION", "schemaVersion"),
        ("ATTESTATION_ID", "attestationId"),
        ("PRODUCER_VERSION", "producerVersion"),
        ("KEY_ID", "keyId"),
        ("SIGNATURE_ALGORITHM", "signatureAlgorithm"),
        ("SECURITY_PROFILE_VERSION", "securityProfileVersion"),
        ("RUNTIME", "runtime"),
        ("SANDBOX_RUNTIME", "sandboxRuntime"),
        ("RUNTIME_SUBJECT", "runtimeSubject"),
        ("RUNTIME_GENERATION", "runtimeGeneration"),
        ("PROBE_IMAGE_DIGEST", "probeImageDigest"),
    ]:
        out += emit(label)
        out += emit(payload[field])

    out += emit("EGRESS_PROXY_IMAGE_DIGEST")
    # Absent is its own value, never the empty string.
    out += emit(payload.get("egressProxyImageDigest") or ABSENT)
    out += emit("ASSESSED_AT")
    out += emit(payload["assessedAt"])

    for label, field in [
        ("MANDATORY_CONTROL", "mandatoryControls"),
        ("EGRESS_CONTROL", "egressControls"),
    ]:
        controls = payload.get(field) or {}
        out += emit(label + "_COUNT")
        out += emit(str(len(controls)))
        # "Ordered by control name using unsigned UTF-16 code-unit order." Every name in the contract is
        # ASCII, so Python's default string order coincides; sorting on the UTF-16 code units is written out
        # rather than assumed, because the rule is stated for the names and not for the current names.
        for name in sorted(controls, key=lambda n: n.encode("utf-16-be")):
            out += emit(label)
            out += emit(name)
            out += emit(controls[name])

    return bytes(out)


def main():
    payload = json.loads((FIXTURES / "canonical-payload.json").read_text())
    keys = json.loads((FIXTURES / "test-keys.json").read_text())["keys"]

    preimage = canonical_preimage(payload)
    digest = "sha256:" + hashlib.sha256(preimage).hexdigest()

    def sign(key_id):
        # PKCS#8 for Ed25519 is a fixed 48-byte structure whose last 32 bytes are the seed. Parsed
        # properly rather than sliced, so a malformed key fails here instead of producing a valid signature
        # from the wrong bytes.
        private = serialization.load_der_private_key(
            base64.b64decode(keys[key_id]["privateKeyPkcs8"]), password=None)
        assert isinstance(private, Ed25519PrivateKey), key_id
        return base64.b64encode(private.sign(preimage)).decode()

    expected = json.loads((FIXTURES / "expected.json").read_text())
    expected["preimageLength"] = len(preimage)
    expected["preimageHex"] = preimage.hex()
    expected["payloadDigest"] = digest
    expected["signature"] = sign("kaas-test-key-1")
    expected["$signatureUnderSecondKey"] = sign("kaas-test-key-2")
    expected["$comment"] = (
        "The expected canonical preimage, digest and signature for canonical-payload.json under "
        "kaas-test-key-1. Fixed in the repository so producer and verifier are each checked against a value "
        "neither of them computed. Generated by scripts/generate-signing-vectors.py, a third implementation "
        "written from the contract document in another language; all three produce these exact "
        f"{len(preimage)} bytes.")
    (FIXTURES / "expected.json").write_text(json.dumps(expected, indent=2) + "\n")

    signed = json.loads((FIXTURES / "valid-signed.json").read_text())
    signed.update(payload)
    signed["payloadDigest"] = digest
    signed["signature"] = expected["signature"]
    (FIXTURES / "valid-signed.json").write_text(json.dumps(signed, indent=2) + "\n")

    generate_negatives(payload, keys, expected["signature"], digest)
    print(f"preimage {len(preimage)} bytes, digest {digest}")


def generate_negatives(valid, keys, signature, digest):
    """
    The refusal vectors, DERIVED from the valid document rather than maintained beside it.

    Hand-written negatives drift: when the schema moved to v4 every one of them still said v3, so each was
    refused at the schema check before reaching the stage it was written to exercise -- a suite of tests that
    all passed while testing one thing. Deriving them means a negative differs from the valid document in
    exactly the one way its name claims, and nothing else.

    The explanation of each lives in invalid/index.json, never inside the document: a comment property is an
    unknown property, and an artifact carrying one is refused as MALFORMED before its actual reason is
    reached.
    """
    out = FIXTURES / "invalid"

    def write(name, document):
        (out / f"{name}.json").write_text(json.dumps(document, indent=2) + "\n")

    def signed(signing_key="kaas-test-key-1", **overrides):
        """A document whose payload is re-signed after the override, so only the named property differs."""
        document = dict(valid)
        document.update(overrides)
        body = {k: v for k, v in document.items() if k not in ("payloadDigest", "signature")}
        preimage = canonical_preimage(body)
        private = serialization.load_der_private_key(
            base64.b64decode(keys[signing_key]["privateKeyPkcs8"]), password=None)
        document["payloadDigest"] = "sha256:" + hashlib.sha256(preimage).hexdigest()
        document["signature"] = base64.b64encode(private.sign(preimage)).decode()
        return document

    def tampered(**overrides):
        """A document edited AFTER signing: digest and signature describe the untampered payload."""
        document = dict(valid)
        document["payloadDigest"] = digest
        document["signature"] = signature
        document.update(overrides)
        return document

    base = dict(valid)
    base["payloadDigest"] = digest
    base["signature"] = signature

    # Edited after signing. Each must be caught by the digest check, before any signature work.
    write("tampered-assessed-at", tampered(assessedAt="2026-09-05T09:12:34Z"))
    write("tampered-profile-version", tampered(securityProfileVersion="kaas.sandbox.airgapped.v1"))
    write("tampered-probe-image-digest", tampered(probeImageDigest="sha256:" + "3" * 64))
    write("tampered-proxy-image-digest", tampered(egressProxyImageDigest="sha256:" + "4" * 64))
    write("tampered-runtime", tampered(runtime="containerd"))
    write("tampered-runtime-subject", tampered(runtimeSubject="kaas.runtime.elsewhere"))
    write("tampered-runtime-generation", tampered(runtimeGeneration="gen:ffffffffffffffffffffffffffffffff"))
    write("tampered-sandbox-runtime", tampered(sandboxRuntime="GVISOR"))

    mandatory = dict(valid["mandatoryControls"])
    mandatory["NO_HOST_MOUNTS"] = "PASS "
    write("tampered-mandatory-verdict", tampered(mandatoryControls=mandatory))

    dropped = dict(valid["mandatoryControls"])
    dropped.pop("NO_DOCKER_SOCKET")
    write("dropped-mandatory-control", tampered(mandatoryControls=dropped))

    egress = dict(valid["egressControls"])
    egress["EGRESS_PROXY_FAILS_CLOSED"] = "FAIL"
    write("tampered-egress-verdict", tampered(egressControls=egress))

    write("tampered-payload-digest", tampered(payloadDigest="sha256:" + "0" * 64))
    write("tampered-signature", tampered(signature=base64.b64encode(b"\x00" * 64).decode()))

    missing = dict(base)
    missing.pop("signature")
    write("missing-signature", missing)

    write("unknown-property", tampered(unexpectedProperty="anything at all"))

    # Genuinely signed, and still refused: the key is not one this deployment pinned.
    # Signed by a real key, then relabelled with an id nothing pinned. Authentic bytes, unresolvable key.
    write("unknown-key-id", signed(keyId="kaas-unknown-key"))
    # Signed by key 2 while CLAIMING key 1. The verifier resolves one key by id and never tries others.
    # The payload is UNCHANGED -- it still claims key 1 -- and only the signature comes from key 2. The
    # digest therefore matches and nothing but signature verification can refuse it, which is what makes this
    # the vector that proves signature verification actually runs. Overriding keyId as well would move the
    # preimage and the cheap digest check would refuse it first, testing the wrong thing.
    write("signed-by-a-different-trusted-key", signed(signing_key="kaas-test-key-2"))
    # Claims key 2, signed by key 1. keyId is inside the preimage, so the digest moves too and the cheap
    # check refuses before any signature work.
    write("key-id-does-not-match-signature", tampered(keyId="kaas-test-key-2"))
    # An algorithm the document does not get to choose.
    write("wrong-algorithm", signed(signatureAlgorithm="ED448"))
    # A superseded runtime claim: the profile version says one boundary, the runtime field says the other.
    write("self-contradictory-runtime", signed(sandboxRuntime="GVISOR"))

    # Superseded schemas, refused rather than downgraded. v2 had no signature at all; v3 was signed under a
    # different domain separator, so it is authentic and still not acceptable.
    v2 = {
        "schemaVersion": "kaas.sandbox-security-attestation.v2",
        "securityProfileVersion": valid["securityProfileVersion"],
        "runtime": valid["runtime"],
        "probeImageDigest": valid["probeImageDigest"],
        "assessedAt": valid["assessedAt"],
        "mandatoryControls": valid["mandatoryControls"],
        "egressControls": valid["egressControls"],
        "digest": digest,
    }
    write("unsigned-v2", v2)
    v3 = {k: v for k, v in valid.items() if k != "sandboxRuntime"}
    v3["schemaVersion"] = "kaas.sandbox-security-attestation.v3"
    v3["payloadDigest"] = digest
    v3["signature"] = signature
    write("superseded-v3", v3)


if __name__ == "__main__":
    main()
